# Generated by Django 4.1.7 on 2023-07-25 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_avatar', models.ImageField(default='../main/static/photos/user.png', upload_to='photos/avatars_imgs')),
                ('user_bg', models.ImageField(default='../main/static/photos/banner_red.png', upload_to='photos/backgr_imgs')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=40)),
                ('prod_count', models.IntegerField(default=1)),
                ('prod_link', models.CharField(max_length=140)),
                ('price', models.IntegerField(default=0)),
                ('descr', models.CharField(max_length=200)),
                ('collectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.collections')),
                ('creatorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('currID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.currency')),
            ],
        ),
        migrations.CreateModel(
            name='AddUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=40)),
                ('instlink', models.CharField(blank=True, max_length=200)),
                ('tglink', models.CharField(blank=True, max_length=200)),
                ('descr_abt_self', models.CharField(max_length=200)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
