# Generated by Django 4.1.7 on 2023-07-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userimages_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='user_avatar',
            field=models.ImageField(default='../main/static/photos/user.png', upload_to='photos/avatars_imgs'),
        ),
    ]
