# Generated by Django 4.1.7 on 2023-07-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userimages_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='collectionID',
        ),
        migrations.RemoveField(
            model_name='card',
            name='creatorID',
        ),
        migrations.RemoveField(
            model_name='card',
            name='currID',
        ),
        migrations.RemoveField(
            model_name='userimages',
            name='userID',
        ),
        migrations.DeleteModel(
            name='AddUserInfo',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Collections',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='UserImages',
        ),
    ]
