# Generated by Django 4.1.7 on 2023-07-27 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_bg', models.ImageField(upload_to='./photos/backgr_imgs')),
                ('customer_avatar', models.ImageField(upload_to='./photos/avatars_imgs')),
                ('customer_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
