# Generated by Django 4.1.7 on 2023-07-28 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_alter_customer_images_customer_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=30)),
                ('inst_link', models.CharField(max_length=100)),
                ('tg_link', models.CharField(max_length=100)),
                ('descr', models.CharField(max_length=100)),
                ('customer_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
