# Generated by Django 4.1.7 on 2023-07-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_customer_data_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_data',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer_data',
            name='follows',
            field=models.IntegerField(default=0),
        ),
    ]
