# Generated by Django 4.1.7 on 2023-07-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_customer_data_followers_customer_data_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_data',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='customer_data',
            name='follows',
        ),
    ]
