# Generated by Django 4.1.7 on 2023-07-30 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_customer_data_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_data',
            name='date_of_reg',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
