# Generated by Django 4.1.7 on 2023-08-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_follower_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follower',
            name='follow system',
        ),
    ]
