# Generated by Django 4.1.7 on 2023-08-10 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_remove_follower_follow system'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain_curr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_collection', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_image', models.ImageField(upload_to='./photos/products')),
                ('item_name', models.CharField(max_length=100)),
                ('count_of_prod', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('date_of_creat', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('blockchainW', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.blockchain')),
                ('collect_relat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.collection')),
            ],
        ),
    ]
